name: Test

on:
  push:
    branches: [main]

jobs:
  client:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./client

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Client - Install Dependencies
      run: npm ci
    - name: Client - Lint
      run: npm run lint
    - name: Client - Log in to Docker Hub
      uses: docker/login-action@3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Client - Build and push Docker image
      uses: docker/build-push-action@5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: latest
  
  server:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./server

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Server - Install Dependencies
      run: npm ci
    - name: Server - Lint
      run: npm run lint
    - name: Server - Build
      run: npm run build
    - name: Server - Log in to Docker Hub
      uses: docker/login-action@3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Server - Build and push Docker image
      uses: docker/build-push-action@5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: latest